# fly.toml app configuration file generated for charlesp-reactivities on 2024-02-19T20:22:50+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'charlesp-reactivities'
primary_region = 'syd'

[build]
  image = 'charlesphan/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dzbb5enbh"
  Cloundinary__ApiKey="774331822433638"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
